// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQypEAh-p9BiWXx9xBPhZy4ZG1RbiioeQ',
    appId: '1:183586310001:web:72389b9c114af0aaf718d0',
    messagingSenderId: '183586310001',
    projectId: 'flutter-chat-app-a10a2',
    authDomain: 'flutter-chat-app-a10a2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a10a2.appspot.com',
    measurementId: 'G-53CVQXBB4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tNrREQXXMps5mDh93MUdzuIf7l55Dkg',
    appId: '1:183586310001:android:4764b16d3bed6851f718d0',
    messagingSenderId: '183586310001',
    projectId: 'flutter-chat-app-a10a2',
    storageBucket: 'flutter-chat-app-a10a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-QxpsESg4xbiS-ZRga4wh6risDjV-Nw',
    appId: '1:183586310001:ios:355b5ba11a1647aef718d0',
    messagingSenderId: '183586310001',
    projectId: 'flutter-chat-app-a10a2',
    storageBucket: 'flutter-chat-app-a10a2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt-QxpsESg4xbiS-ZRga4wh6risDjV-Nw',
    appId: '1:183586310001:ios:355b5ba11a1647aef718d0',
    messagingSenderId: '183586310001',
    projectId: 'flutter-chat-app-a10a2',
    storageBucket: 'flutter-chat-app-a10a2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQypEAh-p9BiWXx9xBPhZy4ZG1RbiioeQ',
    appId: '1:183586310001:web:c575e83cc026117cf718d0',
    messagingSenderId: '183586310001',
    projectId: 'flutter-chat-app-a10a2',
    authDomain: 'flutter-chat-app-a10a2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a10a2.appspot.com',
    measurementId: 'G-ZZKZ04TSJZ',
  );
}
